import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Remove any debug overlays
              if (typeof window !== 'undefined') {
                // Remove React DevTools globals
                if (window.__REACT_DEVTOOLS_GLOBAL_HOOK__) {
                  window.__REACT_DEVTOOLS_GLOBAL_HOOK__.inject = function() {};
                }
                // Clear any debug console methods in production
                if (process.env.NODE_ENV === 'production') {
                  console.log = function() {};
                  console.debug = function() {};
                  console.info = function() {};
                }
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
